apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-bphi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-bphi
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-bphi
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-bphi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-bphi
    spec:
      containers:
      - image: quay.io/rh-gitops-bot/rhtap-demo-pdke-tenant/rhtap-demo-app/hacbs-test-project-bphi@sha256:e79e3b342ff361575c5afaa56c0bf4a6dbc137ec6ec7ac53cb4e5058544f5323
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
